### PR TITLE
Created environment.yml solution for conda

### LINKED ISSUE #12: Develop environment.yml and requirements.txt for baseline earthquake notebook
We need to solve the environment from prior experiments that way we build a basis for future analysis and comparison.  This is tied to #14 , but focuses in on library versions and compatibilities than optimizing the algorithms and code.

Library dependencies that are in the current platform include:

- cloudmesh-common
- matplotlib
- numpy
- pandas
- psutil
- scipy
- tensorflow
- tensorflow_datasets
- tqdm

### PR DESCRIPTION
**Pull request by rknuu**
Closes #12 

Solved environment dependencies.  The version of matplotlib clashed with tensorflow (likely due to a custom build of tensorflow on the google colab ecosystem).  This environment.yml will build a consistent environment.

This PR also has details on how to use lmod and signularity; but these will likely get relocated to the lazewsk/mlcommons repo.

Also added a vscode configuration file to help keep configurations in sync for those that use vscode.

### CODE REVIEW

**Comment by laszewsk** [comment]
To integrate with the mlcommons people i moved the code to 

Earthquake Code: https://github.com/laszewsk/mlcommons/tree/main/benchmarks/earthquake
MNIST Code: https://github.com/laszewsk/mlcommons/tree/main/examples/mnist-tensorflow

I wonder if we wantto do a submodule in this repo, but that may be to complex ... for nowmake mode in the code dir.
Also i propose to stricktly separate git pushes so we do them separate from documentation, I do pushes often
Also before starting to work i suggest to do a git status and git pull

**Review by laszewsk — CHANGES_REQUESTED** [review]
see comment in issue notes for better code location

**Comment by rknuu** [comment]
Have to close this PR as the code is is no longer in this repo.  I'll reconstitute this baseline in the other repo as @laszewsk.

**Comment by laszewsk** [comment]
make sure its reflected also in requirements.txt

**Pull request closed without merging**
